version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: exchanger-db
    environment:
      POSTGRES_DB: exchanger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql

    restart: unless-stopped
    networks:
      - exchanger-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  exchanger-api:
    image: tomcat:10.1-jdk21
    container_name: exchanger-api
    volumes:
      - ./target/exchanger.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - exchanger-net
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=exchanger_db
      - DB_USER=postgres
      - DB_PASSWORD=admin

  nginx:
    image: nginx:alpine
    container_name: exchanger-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - exchanger-api
    restart: unless-stopped
    networks:
      - exchanger-net

volumes:
  postgres_data:

networks:
  exchanger-net: